version: '3'
services:
  api:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3010:3000'
    networks:
      - common
    depends_on:
      - postgres
      - postgres-test
      - redis
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    environment:
      POSTGRES_USER: converter_user
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: converter_db
    networks:
      - common
  postgres-test:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /data/postgres-test:/data/postgres
    environment:
      POSTGRES_USER: test_converter_user
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: test_converter_db
    networks:
      - common
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass q1w2e3r4
    volumes:
      - redis:/data
    networks:
      - common
networks:
  common: {}
volumes:
  redis:
    driver: local
