name: Deploy

on:
  workflow_run:
    workflows: ['CI Tests']
    branches: [master, develop]
    types:
      - completed
  workflow_dispatch:
  push:
    branches: [master, develop]

jobs:
  deploy-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-development
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build . -t converter-service -f docker/Dockerfile
      - run: echo "Deploy development"
  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build . -t converter-service -f docker/Dockerfile
      - run: echo "Deploy production"
