name: E2E Tests

on:
  push:
  pull_request:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          PORT: 3000
          BASE_URL: http://localhost:3000
          DB_NAME: converter_db
          DB_USER: converter_user
          DB_PASSWORD: q1w2e3r4
          DB_HOST: postgres
          DB_PORT: 5432
          TEST_DB_NAME: test_converter_db
          TEST_DB_USER: test_converter_user
          TEST_DB_PASSWORD: q1w2e3r4
          TEST_DB_HOST: postgres-test
          TEST_DB_PORT: 5433
          API_LAYER_URL: https://api.apilayer.com/exchangerates_data
          API_LAYER_KEY: VxCAPMLp1GjJKJDPPIRv84VziwsUzMYa
          HTTP_TIMEOUT: 120000
          HTTP_MAX_REDIRECTS: 5
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Change ownership
        run: sudo chown runner ./node_modules

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Migrate and seed
        run: yarn migrate && yarn seed

      - name: Run tests
        run: yarn run test:e2e

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
