name: E2E Tests

on:
  push:
  pull_request:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Change ownership
        run: sudo chown runner ./node_modules

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Migrate and seed
        run: yarn migrate && yarn seed

      - name: Run tests
        run: yarn run test:e2e

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
